<template>
  <div>
    <div>
      <q-card>
        <q-card-section>
      <q-avatar size = "200px"
      style= "padding-top: 40px; margin-left: 42%">
      <q-img
        src="../statics/json.jpeg"
        class = "avatar"
        style="max-width: 400px; height: 200px;"
      >
      </q-img>
      </q-avatar>
      </q-card-section>
      </q-card>
    </div>
    <div style="padding: 40px; margin: 100px">
    I'm Jason Wei, last year in SFSU, major in Computer Science. Nothing too interesting about me, loves sports and games.
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      name: null
    }
  }
}
</script>

<style>

</style>
